database:
  image: postgres
  ports:
    - "5432:5432"
  volumes:
    - ./database/backups:/backups/
    - ./database/docker-entrypoint-initdb.d/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh

service:
  build: service
  links:
    - database
  ports:
    - "8000:80"
  environment:
    DJANGO_SECRET_KEY: 61x87zb)7p^-tnbcyiy*c89%28^m375wf*63o27=i3xs-v9#z@
    DJANGO_STATIC_ROOT: /srv/waterpower-service/static/
    DJANGO_SETTINGS_MODULE: sources.settings.env.development
    DATABASE_URL: postgres://waterpower_user@database/waterpower_db

  volumes:
    - ./service/.ipython/:/root/.ipython/
    - ./service/manage.py:/srv/waterpower-service/manage.py
    - ./service/static/:/srv/waterpower-service/static/
    - ./service/sources/:/srv/waterpower-service/sources/
    - ./service/fixtures/:/srv/waterpower-service/fixtures/
    - ./service/requirements/:/srv/waterpower-service/requirements/
    - ./service/etc/uwsgi.ini:/srv/waterpower-service/etc/uwsgi.ini
